version: '3.8'
services:
  app:
    image: tmqqq/web:0.0.1-SNAPSHOT
    container_name: web
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pets
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8060:8060"
  db:
    container_name: pets_db
    image: library/postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=pets
      - PGDATA=/var/lib/postgresql/data/pets
    ports:
      - "5433:5432"